//
//  AuthorizationScreenWorker.swift
//  WhoCooler
//
//  Created by Artem Trubacheev on 04.04.2020.
//  Copyright (c) 2020 Artem Trubacheev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import RxSwift

class AuthorizationScreenWorker {

    let networkService = NetworkServiceImplementation.shared
    let userDefaults = UserDefaultsService.shared

    func authorize(with token: AuthToken) -> Observable<UserSession> {
        let args: [String: Any]
        switch token {
        case .facebook(let token), .google(let token):
            args = ["token": token, "platform": "ios"]
        case .apple(let token, let name):
            if let name = name {
                args = ["token": token, "user_name": name, "platform": "ios"]
            } else {
                args = ["token": token, "platform": "ios"]
            }
        }

        return networkService
            .getData(endpoint: "register", parameters: args, method: .post)
            .do(onNext: { [weak self] in
                self?.userDefaults.session = $0
            })
    }

}
