//
//  AuthorizationScreenModels.swift
//  WhoCooler
//
//  Created by Artem Trubacheev on 04.04.2020.
//  Copyright (c) 2020 Artem Trubacheev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AuthorizationScreen {

    // MARK: Use cases
    enum Providers {
        struct Request {}
        struct Response {
            var providers: [AuthProvider]
        }
        struct ViewModel {
            var providers: [AuthProvider]
        }
    }

    enum Authorization {
        struct Request {
            var provider: AuthProvider
        }
        struct Response {}
        struct ViewModel {}
    }

}
