//
//  DebateDetailWorker.swift
//  DebateMaker
//
//  Created by Artem Trubacheev on 09.04.2020.
//  Copyright (c) 2020 Artem Trubacheev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift

class DebateDetailWorker {

    let networkService = NetworkServiceImplementation.shared

    func getDebate(id: String) -> Observable<Debate> {
        networkService.getData(
            endpoint: "debate",
            parameters: ["debate_id": id]
        )
    }

    func getNextMessages(id: String, ctime: Double) -> Observable<MessagesList> {
        networkService.getData(
            endpoint: "messages",
            parameters: ["debate_id": id, "after_time": ctime]
        )
    }

    func getNextReplies(id: String, after: Double) -> Observable<MessagesList> {
        networkService.getData(
            endpoint: "messages",
            parameters: ["thread_id": id, "after_time": after]
        )
    }

    func vote(debateId: String, sideId: String) -> Observable<Empty> {
        networkService.getData(
            endpoint: "vote",
            parameters: ["debate_id": debateId, "side_id": sideId],
            method: .post
        )
    }

    func sendMessage(text: String, debateId: String) -> Observable<Message> {
        networkService.getData(
            endpoint: "message",
            parameters: ["text": text, "debate_id": debateId],
            method: .post
        )
    }

    func sendReply(text: String, threadId: String) -> Observable<Message> {
        networkService.getData(
            endpoint: "message",
            parameters: ["text": text, "thread_id": threadId],
            method: .post
        )
    }
    
}
