//
//  DebateDetailRouter.swift
//  DebateMaker
//
//  Created by Artem Trubacheev on 09.04.2020.
//  Copyright (c) 2020 Artem Trubacheev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DebateDetailRoutingLogic {
    func navigateToAuthorization()
}

protocol DebateDetailDataPassing {
    var dataStore: DebateDetailDataStore? { get }
}

class DebateDetailRouter: NSObject, DebateDetailRoutingLogic, DebateDetailDataPassing {
    
    weak var viewController: DebateDetailViewController?
    var dataStore: DebateDetailDataStore?
  
    // MARK: Routing
    func navigateToAuthorization() {
       viewController?.present(
           AuthorizationScreenViewController(),
           animated: true,
           completion: nil
       )
    }

}
