//
//  DebateListModels.swift
//  DebateMaker
//
//  Created by Artem Trubacheev on 18.01.2020.
//  Copyright (c) 2020 Artem Trubacheev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum DebateList {
  // MARK: Use cases
    enum Something {

        struct Request {
            let categoryId: String?
            let selectedSorting: String
        }

        struct Response {
            let data: [Debate]
            let categories: [Category]
            let hasNextPage: Bool
        }

        struct ViewModel {
            let cells: [CellType]
            let hasNextPage: Bool
        }
    }

    enum Favorites {
        struct PostRequest {
            let debate: Debate
            let isFavorite: Bool
        }
        struct GetRequest {
            let page: Int
        }
    }

    enum CellType {
        case categoryList([Category])
        case debate(Debate)
        case new
        case emptyFavorites
        case custdev(style: CustdevStyle)
    }

}
