//
//  DebateListRouter.swift
//  DebateMaker
//
//  Created by Artem Trubacheev on 18.01.2020.
//  Copyright (c) 2020 Artem Trubacheev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DebateListRoutingLogic {
    func navigateToDebate(_ debate: Debate)
    func navigateToProfile()
    func navigateToSearch()
}

protocol DebateListDataPassing {}

class DebateListRouter: NSObject, DebateListRoutingLogic, DebateListDataPassing {

    weak var viewController: DebateListViewController?

    let userDefaults = UserDefaultsService.shared

    // MARK: Navigation
    func navigateToDebate(_ debate: Debate) {
        viewController?.navigationController?.pushViewController(
            DebateDetailViewController(debate: debate),
            animated: true
        )
    }

    func navigateToProfile() {
        if userDefaults.session == nil {
            viewController?.present(
                AuthorizationScreenViewController(),
                animated: true,
                completion: nil
            )
        } else {
            viewController?.present(
                UserProfileViewController(),
                animated: true,
                completion: nil
            )
        }
    }

    func navigateToSearch() {
        viewController?.navigationController?.pushViewController(
            SearchViewController(),
            animated: true
        )
    }

}
