//
//  DiscussionListRouter.swift
//  DiscussionMaker
//
//  Created by Artem Trubacheev on 18.01.2020.
//  Copyright (c) 2020 Artem Trubacheev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DiscussionListRoutingLogic {
    func navigateToDebate(_ debate: Discussion)
    func navigateToProfile()
}

protocol DiscussionListDataPassing {}

class DiscussionListRouter: NSObject, DiscussionListRoutingLogic, DiscussionListDataPassing {

    weak var viewController: DiscussionListViewController?

    let userDefaults = UserDefaultsService.shared

    // MARK: Navigation
    func navigateToDebate(_ debate: Discussion) {
        viewController?.navigationController?.pushViewController(
            DiscussionDetailViewController(debate: debate),
            animated: true
        )
    }

    func navigateToProfile() {
        if userDefaults.session == nil {
            viewController?.present(
                AuthorizationScreenViewController(),
                animated: true,
                completion: nil
            )
        } else {
            viewController?.present(
                UserProfileViewController(),
                animated: true,
                completion: nil
            )
        }
    }

}
