//
//  DiscussionListRouter.swift
//  DiscussionMaker
//
//  Created by Artem Trubacheev on 18.01.2020.
//  Copyright (c) 2020 Artem Trubacheev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DiscussionListRoutingLogic {
    func navigateToDebate(_ debate: Discussion)
}

protocol DiscussionListDataPassing
{
}

class DiscussionListRouter: NSObject, DiscussionListRoutingLogic, DiscussionListDataPassing {

    weak var viewController: DiscussionListViewController?

    // MARK: Navigation
    func navigateToDebate(_ debate: Discussion) {
        viewController?.show(
            DiscussionDetailViewController(debate: debate),
            sender: viewController
        )
    }

}
