//
//  DiscussionListPresenter.swift
//  DiscussionMaker
//
//  Created by Artem Trubacheev on 18.01.2020.
//  Copyright (c) 2020 Artem Trubacheev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DiscussionListPresentationLogic {
    func presentSomething(response: DiscussionList.Something.Response)
}

class DiscussionListPresenter: DiscussionListPresentationLogic {
    weak var viewController: DiscussionListDisplayLogic?

    // MARK: Do something
    func presentSomething(response: DiscussionList.Something.Response) {
        let cells: [DiscussionList.CellType] = response.data.map { .discussionLink($0) }

        let viewModel = DiscussionList.Something.ViewModel(cells: cells)
        viewController?.displaySomething(viewModel: viewModel)
    }

}
