//
//  DiscussionListWorker.swift
//  DiscussionMaker
//
//  Created by Artem Trubacheev on 18.01.2020.
//  Copyright (c) 2020 Artem Trubacheev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Alamofire
import RxSwift

class DiscussionListWorker {

    let networkService = NetworkServiceImplementation.shared

    func getDiscussions(
        page: Int = 1,
        categoryId: String? = Category.all.id,
        sorting: String
    ) -> Observable<DebatesResponse> {
        networkService.getData(
            endpoint: "debates",
            parameters: [
                "page": page,
                "sorting": sorting,
                "category_id": categoryId ?? Category.all.id
            ],
            shouldLocalize: true
        )
    }

    func toggleFavorites(request: DiscussionList.Favorites.PostRequest) -> Observable<Empty> {
        if request.isFavorite {
            return deleteFromFavorites(debateId: request.debate.id)
        } else {
            return addToFavorites(debateId: request.debate.id)
        }
    }

    private func addToFavorites(debateId: String) -> Observable<Empty> {
        networkService.getData(
            endpoint: "favorites",
            parameters: ["debate_id": debateId],
            method: .post
        )
    }

    private func deleteFromFavorites(debateId: String) -> Observable<Empty> {
        networkService.getData(
            endpoint: "favorites",
            parameters: ["debate_id": debateId],
            method: .delete
        )
    }

}
