//
//  DiscussionListWorker.swift
//  DiscussionMaker
//
//  Created by Artem Trubacheev on 18.01.2020.
//  Copyright (c) 2020 Artem Trubacheev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Alamofire
import UIKit
import RxSwift

class DiscussionListWorker {

    let baseUrl = "https://debates-rest-api7.herokuapp.com"

    func getDiscussions() -> Observable<DebatesResponse> {
        let response = PublishSubject<DebatesResponse>()
        AF.request(
            "\(baseUrl)/debates",
            method: .get
        ).responseData {
            guard let data = $0.data else {
                response.onError(AFError.explicitlyCancelled)
                return
            }

            let debates = try? JSONDecoder().decode(DebatesResponse.self, from: data)

            guard let unwrappedDebates = debates else {
                response.onError(AFError.explicitlyCancelled)
                return
            }

            response.onNext(unwrappedDebates)
        }

        return response
    }

}
