//
//  DiscussionListWorker.swift
//  DiscussionMaker
//
//  Created by Artem Trubacheev on 18.01.2020.
//  Copyright (c) 2020 Artem Trubacheev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Alamofire
import UIKit
import RxSwift

class DiscussionListWorker {

    let networkService = NetworkServiceImplementation.shared

    func getDiscussions(page: Int = 1) -> Observable<DebatesResponse> {
        networkService.getData(
            endpoint: "debates",
            parameters: ["page": page],
            shouldLocalize: true
        )
    }

}
