//
//  UserProfileRouter.swift
//  WhoCooler
//
//  Created by Artem Trubacheev on 24.04.2020.
//  Copyright (c) 2020 Artem Trubacheev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol UserProfileRoutingLogic {
    func dismiss()
}

protocol UserProfileDataPassing
{
    var dataStore: UserProfileDataStore? { get }
}

class UserProfileRouter: NSObject, UserProfileRoutingLogic, UserProfileDataPassing {

    weak var viewController: UserProfileViewController?
    var dataStore: UserProfileDataStore?

    // MARK: Routing
    func dismiss() {
        viewController?.dismiss(animated: true, completion: nil)
    }

}
