//
//  UserProfilePresenter.swift
//  WhoCooler
//
//  Created by Artem Trubacheev on 24.04.2020.
//  Copyright (c) 2020 Artem Trubacheev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserProfilePresentationLogic {
    func presentProfile(response: UserProfile.Profile.Response)
    func didLogOut()
}

class UserProfilePresenter: UserProfilePresentationLogic {
    weak var viewController: UserProfileDisplayLogic?

    // MARK: Do something
    func presentProfile(response: UserProfile.Profile.Response) {
        viewController?.displayProfile(
            viewModel: .init(
                user: response.user,
                pushToken: response.pushToken,
                accessToken: response.accessToken
            )
        )
    }

    func didLogOut() {
        viewController?.dismiss()
    }

}
