//
//  DiscussionDetailPresenter.swift
//  DiscussionMaker
//
//  Created by Artem Trubacheev on 09.04.2020.
//  Copyright (c) 2020 Artem Trubacheev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DiscussionDetailPresentationLogic {
    func presentSomething(response: DiscussionDetail.Something.Response)
}

class DiscussionDetailPresenter: DiscussionDetailPresentationLogic {

    weak var viewController: DiscussionDetailDisplayLogic?

    // MARK: Do something
    func presentSomething(response: DiscussionDetail.Something.Response) {
        let viewModel = DiscussionDetail.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }

}
