//
//  DiscussionDetailInteractor.swift
//  DiscussionMaker
//
//  Created by Artem Trubacheev on 09.04.2020.
//  Copyright (c) 2020 Artem Trubacheev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DiscussionDetailBusinessLogic {
    func doSomething(request: DiscussionDetail.Something.Request)
}

protocol DiscussionDetailDataStore {}

class DiscussionDetailInteractor: DiscussionDetailBusinessLogic, DiscussionDetailDataStore {

    var presenter: DiscussionDetailPresentationLogic?
    var worker: DiscussionDetailWorker?

    // MARK: Do something
    func doSomething(request: DiscussionDetail.Something.Request) {
        worker = DiscussionDetailWorker()
        worker?.doSomeWork()

        let response = DiscussionDetail.Something.Response()
        presenter?.presentSomething(response: response)
    }

}
