//
//  CreateDebatePresenter.swift
//  WhoCooler
//
//  Created by Artem Trubacheev on 31.05.2020.
//  Copyright (c) 2020 Artem Trubacheev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateDebatePresentationLogic {
    func presentSomething(response: CreateDebate.Creation.Response)
}

class CreateDebatePresenter: CreateDebatePresentationLogic {
    weak var viewController: CreateDebateDisplayLogic?

    // MARK: Do something
    func presentSomething(response: CreateDebate.Creation.Response) {
        let viewModel = CreateDebate.Creation.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
