//
//  CreateDebateModels.swift
//  WhoCooler
//
//  Created by Artem Trubacheev on 31.05.2020.
//  Copyright (c) 2020 Artem Trubacheev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CreateDebate {

    // MARK: Use cases
    enum Creation {
        enum Sides {
            struct Request {
                let leftName: String
                let rightName: String
                let leftImage: UIImage
                let rightImage: UIImage
                let categoryId: String
                let name: String?
            }
            struct Response {}
            struct ViewModel {}
        }
        enum Statement {
            struct Request {
                let leftName: String
                let rightName: String
                let debateImage: UIImage
                let categoryId: String
                let name: String
            }
            struct Response {}
            struct ViewModel {}
        }
    }

}
