//
//  CreateDebateRouter.swift
//  WhoCooler
//
//  Created by Artem Trubacheev on 31.05.2020.
//  Copyright (c) 2020 Artem Trubacheev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CreateDebateRoutingLogic {}

protocol CreateDebateDataPassing {
    var dataStore: CreateDebateDataStore? { get }
}

class CreateDebateRouter: NSObject, CreateDebateRoutingLogic, CreateDebateDataPassing {
    weak var viewController: CreateDebateViewController?
    var dataStore: CreateDebateDataStore?
}
