//
//  AuthorizationScreenInteractor.swift
//  DiscussionMaker
//
//  Created by Artem Trubacheev on 04.04.2020.
//  Copyright (c) 2020 Artem Trubacheev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AuthorizationScreenBusinessLogic
{
  func doSomething(request: AuthorizationScreen.Something.Request)
}

protocol AuthorizationScreenDataStore
{
  //var name: String { get set }
}

class AuthorizationScreenInteractor: AuthorizationScreenBusinessLogic, AuthorizationScreenDataStore
{
  var presenter: AuthorizationScreenPresentationLogic?
  var worker: AuthorizationScreenWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: AuthorizationScreen.Something.Request)
  {
    worker = AuthorizationScreenWorker()
    worker?.doSomeWork()
    
    let response = AuthorizationScreen.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
