//
//  AuthorizationScreenPresenter.swift
//  DiscussionMaker
//
//  Created by Artem Trubacheev on 04.04.2020.
//  Copyright (c) 2020 Artem Trubacheev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AuthorizationScreenPresentationLogic
{
  func presentSomething(response: AuthorizationScreen.Something.Response)
}

class AuthorizationScreenPresenter: AuthorizationScreenPresentationLogic
{
  weak var viewController: AuthorizationScreenDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: AuthorizationScreen.Something.Response)
  {
    let viewModel = AuthorizationScreen.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
