//
//  AuthorizationScreenPresenter.swift
//  DiscussionMaker
//
//  Created by Artem Trubacheev on 04.04.2020.
//  Copyright (c) 2020 Artem Trubacheev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AuthorizationScreenPresentationLogic {
    func presentProviders(response: AuthorizationScreen.Providers.Response)
    func didFinishAuth(response: AuthorizationScreen.Authorization.Response)
}

class AuthorizationScreenPresenter: AuthorizationScreenPresentationLogic {

    weak var viewController: AuthorizationScreenDisplayLogic?

    // MARK: Do something
    func presentProviders(response: AuthorizationScreen.Providers.Response) {
        viewController?.displayProviders(
            viewModel: .init(providers: response.providers)
        )
    }

    func didFinishAuth(response: AuthorizationScreen.Authorization.Response) {
        viewController?.didEndAuth(viewModel: .init())
    }

}
