//
//  PickCategoryModels.swift
//  WhoCooler
//
//  Created by Artem Trubacheev on 06.06.2020.
//  Copyright (c) 2020 Artem Trubacheev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PickCategory {

    enum GetCategories {
        struct Response {
            var categories: [Category]
        }
        struct ViewModel {
            var categories: [Category]
        }
    }

    enum Search {
        struct Request {
            let searchContext: String
        }
        struct Response {}
        struct ViewModel {}
    }

    enum Create {
        struct Request {
            let name: String
        }
        struct Response {
            let category: Category
        }
        struct ViewModel {}
    }

}
