//
//  PickCategoryViewController.swift
//  WhoCooler
//
//  Created by Artem Trubacheev on 06.06.2020.
//  Copyright (c) 2020 Artem Trubacheev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias SelectionHandler = (Category) -> ()
protocol PickCategoryDisplayLogic: class {
    func displayCategories(viewModel: PickCategory.GetCategories.ViewModel)
}

class PickCategoryViewController: UIViewController, PickCategoryDisplayLogic {

    var interactor: PickCategoryBusinessLogic?
    var router: (NSObjectProtocol & PickCategoryRoutingLogic & PickCategoryDataPassing)?
    var selectionHandler: SelectionHandler?

    // MARK: - Subviews
    private lazy var tableView = UITableView().with {
        $0.delegate = self
        $0.dataSource = self
    }

    // MARK: - Properties
    var categories: [Category] = [] {
        didSet {
            tableView.reloadData()
        }
    }

    // MARK: - Object lifecycle
    convenience init(selectionHandler: SelectionHandler?) {
        self.init()
        self.selectionHandler = selectionHandler
    }

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: - Setup
    private func setup() {
        let viewController = self
        let interactor = PickCategoryInteractor()
        let presenter = PickCategoryPresenter()
        let router = PickCategoryRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: - Routing
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    // MARK: - View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()

        view.backgroundColor = .white
        interactor?.requestCategoryList()
        view.addSubviews(tableView)
    }

    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()

        tableView.pin.all()
    }

    func displayCategories(viewModel: PickCategory.GetCategories.ViewModel) {
        self.categories = viewModel.categories
    }

}

extension PickCategoryViewController: UITableViewDelegate, UITableViewDataSource {

    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        categories.count
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.cell(for: UITableViewCell.self)
        cell.textLabel?.text = categories[indexPath.row].name

        return cell
    }

    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let category = categories[indexPath.row]
        selectionHandler?(category)

        self.dismiss(animated: true, completion: nil)
    }

}
