//
//  PickCategoryInteractor.swift
//  WhoCooler
//
//  Created by Artem Trubacheev on 06.06.2020.
//  Copyright (c) 2020 Artem Trubacheev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift

protocol PickCategoryBusinessLogic {
    func requestCategoryList()
}

protocol PickCategoryDataStore {}

class PickCategoryInteractor: PickCategoryBusinessLogic, PickCategoryDataStore {

    var presenter: PickCategoryPresentationLogic?
    var worker: PickCategoryWorker = PickCategoryWorker()

    let disposeBag = DisposeBag()

    func requestCategoryList() {
        worker.getCategories()
            .subscribe(onNext: { [weak self] in
                self?.presenter?.didFetchСategories(response: .init(categories: $0.categories))
            }).disposed(by: disposeBag)
    }

}
