//
//  PickCategoryRouter.swift
//  WhoCooler
//
//  Created by Artem Trubacheev on 06.06.2020.
//  Copyright (c) 2020 Artem Trubacheev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PickCategoryRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol PickCategoryDataPassing
{
  var dataStore: PickCategoryDataStore? { get }
}

class PickCategoryRouter: NSObject, PickCategoryRoutingLogic, PickCategoryDataPassing
{
  weak var viewController: PickCategoryViewController?
  var dataStore: PickCategoryDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: PickCategoryViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: PickCategoryDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
