//
//  UserProfileInteractor.swift
//  DiscussionMaker
//
//  Created by Artem Trubacheev on 24.04.2020.
//  Copyright (c) 2020 Artem Trubacheev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserProfileBusinessLogic {
    func getProfile(request: UserProfile.Profile.Request)
}

protocol UserProfileDataStore {}

class UserProfileInteractor: UserProfileBusinessLogic, UserProfileDataStore {

    let userDefaults = UserDefaultsService.shared

    var presenter: UserProfilePresentationLogic?
    var worker: UserProfileWorker?

    // MARK: Do something
    func getProfile(request: UserProfile.Profile.Request) {
        guard
            let session = userDefaults.session,
            let pushToken = userDefaults.fcmToken
        else { return }

        presenter?.presentProfile(
            response: .init(
                user: session.user,
                pushToken: pushToken,
                accessToken: session.accessToken
            )
        )
    }

}
