//
//  UserProfileWorker.swift
//  DiscussionMaker
//
//  Created by Artem Trubacheev on 24.04.2020.
//  Copyright (c) 2020 Artem Trubacheev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift

class UserProfileWorker {

    let networkService = NetworkServiceImplementation.shared

    func modifyProfile(avatar: UIImage?, name: String?) -> Observable<UserEditResponse> {
        var params: [String: Any] = [:]

        if let avatar = avatar { params["avatar"] = avatar.jpegData(compressionQuality: 0.7) }
        if let name = name { params["name"] = name }

        return networkService.updateProfile(name: name, avatar: avatar)
    }

}
